""" Practice

"""

import numpy as np
import functions

#-------------------------------------------------------------------------------

def problem_1(N=1000):
    """ If we list all the natural numbers below 10 that are multiples of 
    3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

    Find the sum of all the multiples of 3 or 5 below 1000.

    """

    natural_numbers = np.arange(N)

    index = np.where( np.logical_not(natural_numbers % 3) | 
                      np.logical_not(natural_numbers % 5) )

    return natural_numbers[index].sum()

#-------------------------------------------------------------------------------

def problem_2(limit=4e6):
    """ Each new term in the Fibonacci sequence is generated by adding the 
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not 
    exceed four million, find the sum of the even-valued terms.

    """

    # This could be made much faster
    
    sum = 0
    iteration = 0
    current = functions.fibonacci(iteration)
    
    while current < limit:

        if not current % 2:
            sum += current

        iteration += 1
        current = functions.fibonacci(iteration)
        
    return sum

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    print "Problem 1: ", problem_1()
    print "Problem 2: ", problem_2()
